packages:
  - packages/*
peerDependencyRules:
  ignoreMissing:
    - eslint-plugin-import
    - eslint
allowedDeprecatedVersions:
  source-map-resolve: '*'
  resolve-url: '*'
  source-map-url: '*'
  urix: '*'
  q: '*'
strictPeerDependencies: false
allowBuilds:
  esbuild: true
  onnxruntime-node: false
  protobufjs: false
  sharp: false
pmOnFail: warn
minimumReleaseAgeExclude:
  - '@vencord/*'
